# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('alt', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(upload_to=projects.models.images_directory_path)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Optional description.')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to=projects.models.project_directory_path)),
                ('short_description', models.CharField(help_text='The text appears on homepage', max_length=100)),
                ('description', models.TextField()),
                ('extra_info', models.TextField(default='default', help_text='About section')),
                ('about_text', models.TextField(blank=True, help_text='No html needed, Converts always to caps', null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=60, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=160, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image_background_page', models.ImageField(blank=True, help_text='Its for the background page cover, uf left black, it will appear black', null=True, upload_to='')),
                ('css_background_color', models.CharField(blank=True, help_text='Use hex color or colors like blue etc', max_length=50, null=True, verbose_name='Background Color')),
                ('css_font_color', models.CharField(blank=True, help_text='Use hex color or colors like blue etc', max_length=50, null=True, verbose_name='Font Color')),
                ('css_font_style', models.CharField(default='sans-serif', help_text='Use hex color or colors like blue etc', max_length=50, verbose_name='Font Style')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectCategory')),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('percent', models.IntegerField(default=50)),
                ('color_bar', models.CharField(blank=True, help_text='Optional changes the color of the bar, Use hex colors to be sure.', max_length=100, null=True)),
                ('project_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
            ],
            options={
                'verbose_name_plural': 'Skill Bar',
            },
        ),
        migrations.AddField(
            model_name='imageproject',
            name='project_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
        ),
    ]
