# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170512_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageproject',
            options={'verbose_name_plural': '2. Gallery'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name_plural': '3. List of Categories.'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': '1. List of Projects'},
        ),
        migrations.AlterModelOptions(
            name='skillprogress',
            options={'verbose_name_plural': '4. Skill Bar on About Page'},
        ),
        migrations.AddField(
            model_name='projects',
            name='css_background_color_menu',
            field=models.CharField(blank=True, help_text='Use hex color or colors like blue etc', max_length=50, null=True, verbose_name='Menu Background Color'),
        ),
        migrations.AddField(
            model_name='projects',
            name='href_color',
            field=models.CharField(blank=True, help_text='Use hex color or colors like blue etc', max_length=50, null=True, verbose_name='Href Color'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='css_background_color',
            field=models.CharField(blank=True, help_text='Use hex color or colors like blue etc', max_length=50, null=True, verbose_name='Page Background Color'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_background_page',
            field=models.ImageField(blank=True, help_text='Its for the background page cover, uf left black, it will appear black', null=True, upload_to=projects.models.project_directory_path),
        ),
    ]
