# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 18:46
from __future__ import unicode_literals

import art.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='The image thats appears on homepage', upload_to=art.models.art_directory_path)),
                ('short_description', models.CharField(help_text='The text appears on homepage, no use of html', max_length=100)),
                ('description', models.TextField(blank=True, help_text='The full description for the art page. HTML USE', null=True)),
                ('slug', models.SlugField(blank=True, help_text='Dont change it!!', null=True)),
                ('seo_title', models.CharField(blank=True, max_length=60, null=True)),
                ('seo_description', models.CharField(blank=True, help_text='The text thats appears on google for the site description. If left null will get the first 160 characters from description.', max_length=160, null=True)),
                ('seo_keywords', models.CharField(blank=True, help_text='Use words that appears oon text, synonyms and no spam for better use.', max_length=160, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image_background_page', models.ImageField(blank=True, help_text='Its for the background page cover, uf left black, it will appear black', null=True, upload_to=art.models.art_background_directory_path)),
                ('css_background_color', models.CharField(blank=True, help_text='Use hex color or colors like blue etc', max_length=50, null=True, validators=[art.models.validate_hex_color], verbose_name='Background Color')),
                ('css_font_color', models.CharField(blank=True, help_text='Use hex color or colors like blue etc', max_length=50, null=True, validators=[art.models.validate_hex_color], verbose_name='Font Color')),
                ('css_font_style', models.CharField(default='sans-serif', help_text='Use hex color or colors like blue etc', max_length=50, verbose_name='Font Style')),
            ],
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ImageArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('alt', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(upload_to=art.models.user_directory_path)),
                ('active', models.BooleanField(default=True)),
                ('project_related', models.ForeignKey(help_text='Pick the project image is related', on_delete=django.db.models.deletion.CASCADE, to='art.Art')),
            ],
        ),
    ]
