# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20170512_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name_plural': '1. List of Arts'},
        ),
        migrations.AlterModelOptions(
            name='imageart',
            options={'verbose_name_plural': '2. Gallery'},
        ),
    ]
