# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 23, 42, 52, 330532)),
        ),
    ]
