# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 06:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20170508_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 9, 11, 11, 551956)),
        ),
    ]
