# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 06:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20170512_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 9, 13, 15, 617615)),
        ),
    ]
