# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 05:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20170512_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 8, 19, 23, 613804)),
        ),
    ]
