# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20170516_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 9, 7, 27, 785713)),
        ),
    ]
