# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', max_length=50)),
                ('text', models.TextField(blank=True, help_text='Use HTML if you want!')),
            ],
            options={
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='AboutMeBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('percent', models.IntegerField(default=50, verbose_name='Number')),
                ('icon', models.CharField(help_text='Here you use bootstrap icons, you can find them here. http://bootstrapmaster.com/live/one/icons_set2.html', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'The stats on front_page',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('day_added', models.DateField(auto_now=True)),
                ('is_readed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banner/')),
                ('header_message', models.CharField(default='George Avdoulos', help_text='Banner header message', max_length=100)),
                ('text_message', models.TextField(default='Le Vavour Illustrator - Designer', help_text='Banner text message')),
                ('color_text', models.CharField(default='#ffffff', max_length=10)),
                ('font', models.CharField(default='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,100%7CRoboto:400,700,300,100', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Main Banner',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Here you use bootstrap icons, you can find them here. http://bootstrapmaster.com/live/one/icons_set2.html', max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(help_text='If you frontpage problems use <br> on end of line', max_length=400)),
                ('order', models.IntegerField(default=1, help_text='Set the order if you want.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Welcome_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to=homepage.models.upload_photo)),
                ('second_banner', models.ImageField(null=True, upload_to=homepage.models.upload_photo)),
                ('my_skills_section_message', models.CharField(default='Would you like to know more or just discuss something?', help_text='NO HTML here.', max_length=160)),
                ('projects_section_message', models.CharField(default='My works so far', help_text='NO HTML here.', max_length=160)),
                ('art_section_message', models.CharField(default='See my demo sites and the future apps.', help_text='NO HTML here.', max_length=160)),
                ('blog_section_message', models.CharField(default="See our latest posts in <a href='www.vavaourasblog.com!'>www.vavaourasblog.com!</a>", help_text='USE HTML here.', max_length=160)),
                ('seo_title', models.CharField(blank=True, help_text='Dont change it!', max_length=60, null=True)),
                ('seo_keywords', models.CharField(blank=True, help_text='Use words that appears oon text, synonyms and no spam for better use.', max_length=160, null=True)),
                ('seo_description', models.CharField(blank=True, help_text='The text thats appears on google for the site description.', max_length=160, null=True)),
                ('about_me', models.CharField(default='ABOUT ME', max_length=20)),
                ('about_me_image', models.ImageField(null=True, upload_to=homepage.models.upload_photo)),
                ('personal_photo', models.ImageField(null=True, upload_to=homepage.models.upload_photo)),
                ('my_skills', models.CharField(default='MY SKILLS', max_length=20)),
                ('project', models.CharField(default='Projects', max_length=20)),
                ('left_text', models.TextField(default='Left part')),
                ('center_text', models.TextField(default='Center part')),
                ('right_text', models.TextField(default='Right part')),
                ('body_background_color', models.CharField(default='', max_length=10, verbose_name='Background Color of all page')),
                ('menu_hover_color', models.CharField(default='', max_length=10, verbose_name='Menu hover color')),
                ('skills_color_primary', models.CharField(default='#13836c', help_text='Change the color on service section', max_length=10, verbose_name='Service Primary color')),
                ('skills_color_secondary', models.CharField(default='#45b59e', max_length=10, verbose_name='Service Secondary  Color')),
                ('main_color_fonts', models.CharField(default='#f4d9d9', max_length=10)),
                ('secondary_color_font', models.CharField(default='#f4d9d9', max_length=10, verbose_name='Menu color and paragraphs etc')),
                ('third_color_font', models.CharField(blank=True, default='#f4d9d9', help_text='Not used atm', max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Welcome Page',
            },
        ),
    ]
