# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome_page',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='welcome_page',
            name='blog_section_message',
            field=models.CharField(default="See our latest posts in <a href='www.vavourasblog.com!'>www.vavourasblog.com!</a>", help_text='USE HTML here.', max_length=160),
        ),
    ]
