# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170507_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': '3. About Section'},
        ),
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'verbose_name_plural': '2. Control the main banner'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['order'], 'verbose_name_plural': '4. Skill Set on front pages'},
        ),
        migrations.AlterModelOptions(
            name='welcome_page',
            options={'verbose_name_plural': '1.Anything about index page'},
        ),
        migrations.AlterField(
            model_name='welcome_page',
            name='third_color_font',
            field=models.CharField(blank=True, default='#f4d9d9', help_text='You control here the titles of projects and the urls.', max_length=10, null=True, verbose_name='Ahref color controller'),
        ),
    ]
